### ISSUE TITLE
Maximum number of elements on the stack

### ISSUE THREAD

**Issue by shilch** [bitcoin-sv-specs/protocol#8]
The Genesis hard fork specification doesn't mention any protocol limit on the number of stack items. Is this on purpose, i.e. could it hold an unbounded number of elements? Or is it `UINT32_MAX` ($2^32 - 1$) as with the length of an element?

**Comment by Danconnolly** [comment]
It is on purpose. There is the "Stack Memory Usage Consensus Rule" which limits the amount of memory that can be used on the stacks. The formula for calculating the memory used on the stack includes an overhead per stack item (32 bytes), which imposes an upper bound on the number of stack elements.

**Comment by shilch** [comment]
Thanks for clarification!
